//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceReferencePortal.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string supply_ids { get; set; }
        public string date_created { get; set; }
        public string created_by { get; set; }
        public string procurement_approval { get; set; }
        public string proc_approval_date { get; set; }
        public string proc_approve_by { get; set; }
        public string accounting_approval { get; set; }
        public string acc_approve_date { get; set; }
        public string acc_approve_by { get; set; }
    }
}
