//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceReferencePortal.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class supplyEntity : DbContext
    {

        public supplyEntity()
            : base("name=supplyEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<supply> supplies { get; set; }

      

        public System.Data.Entity.DbSet<PriceReferencePortal.Context.orderDetail> orderDetails { get; set; }
    }
}
